blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/thelegendtubaguy/ArrQueueCleaner/security/advisories/new
    about: Report security vulnerabilities privately
